services:
  app:
    deploy:
      placement:
        constraints: [node.role == manager]
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000"]
      interval: 10s
      timeout: 5s
      retries: 3
    build: .
    expose:
      - "3000"
    environment:
      - NITRO_HOST=0.0.0.0
      - NITRO_PORT=3000
      - HOST=0.0.0.0
      - PORT=3000
      - NITRO_DEV=false
      - NODE_ENV=production
      - NITRO_PRESET=bun# Or bun if custom
    networks:
      - dokploy-network

  nginx:
    deploy:
      placement:
        constraints: [node.role == manager]
    image: nginx:alpine
    depends_on:
      - app
    expose:
      - "80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - nginx-cache:/var/cache/nginx
    networks:
      - dokploy-network

networks:
  dokploy-network:
    external: true

volumes:
  nginx-cache:
